name: Post-deploy Check

on:
  workflow_run:
    workflows: ["Deploy to Heroku"]
    types:
      - completed

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    # Запускаем только если деплой прошел успешно
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Wait for Heroku to wake up
        run: |
          echo "Waiting for Heroku app to wake up..."
          sleep 30

      - name: Check site availability
        run: |
          echo "Checking if site is accessible..."

          # Проверяем доступность сайта (принимаем любой HTTP код, даже 503)
          for i in {1..5}; do
            echo "Attempt $i/5..."

            # Делаем запрос и получаем HTTP код
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://vdcp26-c16bb5775681.herokuapp.com || echo "000")

            echo "Got HTTP code: $HTTP_CODE"

            # Если получили 200, 301, 302 - все хорошо
            if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "301" ] || [ "$HTTP_CODE" = "302" ]; then
              echo "✅ Site is accessible! HTTP $HTTP_CODE"
              exit 0
            fi

            # Если 503 - приложение еще просыпается
            if [ "$HTTP_CODE" = "503" ]; then
              echo "Site is waking up (503)... waiting 10 seconds"
              sleep 10
              continue
            fi

            # Другой код - ждем и пробуем еще
            echo "Unexpected code: $HTTP_CODE, waiting 5 seconds..."
            sleep 5
          done

          echo "❌ Site failed to respond correctly after 5 attempts"
          exit 1

      - name: Test page content
        run: |
          echo "Fetching page content..."

          # Получаем содержимое страницы
          CONTENT=$(curl -s https://vdcp26-c16bb5775681.herokuapp.com)

          # Проверяем, что HTML не пустой
          if [ -z "$CONTENT" ]; then
            echo "❌ Page content is empty"
            exit 1
          fi

          # Проверяем, что есть базовая HTML структура
          if ! echo "$CONTENT" | grep -q "<html"; then
            echo "❌ No HTML tag found in response"
            exit 1
          fi

          # Проверяем, что нет явных ошибок Heroku
          if echo "$CONTENT" | grep -qi "application error"; then
            echo "❌ Heroku application error detected"
            exit 1
          fi

          echo "✅ Page content looks good!"

      - name: Comment on commit (if failed)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const sha = '${{ github.event.workflow_run.head_sha }}';
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
              body: '❌ Post-deploy check failed. Site is not accessible or returning errors. Check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            });
